### ISSUE TITLE
Empty string returned

### ISSUE THREAD

**Issue by SteinSblitz** [Keeper-Security/aws-credential-process#18]
**Description of the issue**

I am trying to get the keys by running the binary: `keeper-aws-credential-process --uid [uid]`
But I get empty strings in return.
I checked the source code and set the record label correctly on Keeper to "Access Key ID" and "Secret Access Key" as described in the doc as well.
I have the KSM config set up and getting past the authentication.
The record is in the correct shared folder in Keeper since I am not getting errors related to that anymore.
I also tried using no spaces in the label and few other formats.

**Expected behavior**

{"Version":1,"AccessKeyId":"some key","SecretAccessKey":"some key"}

**Actual behavior**

{"Version":1,"AccessKeyId":"","SecretAccessKey":""}

**Your environment**

I am using keeper-aws-credential-process-v0.1.1_linux_amd64 on CentOS 7

**Steps to reproduce**

![image](https://github.com/Keeper-Security/aws-credential-process/assets/7236457/1b377970-073d-447b-a3cc-34215cd1d11c)

**Comment by EndlessTrax** [comment]
Thank you for your issue @SteinSblitz.

It looks like from the screenshot you have `Access Key ID` and `Secret Access Key` nested under custom fields, and not at the top level. The integration currently expects them at the top level. 

Is the information in the custom fields the same as the information in the top-level fields in you `AWS Access Key ID` and `AWS Secret Access Key`? If so, I would recommend you change those field names and remove the custom field variants. If not, then best practice would be to split them out into their own record. 

Please let me know if there is something I'm missing or a use case that hasn't been considered that requires custom field support. Happy to discuss further.

**Comment by SteinSblitz** [comment]
I didn't realize the custom fields are nested.
It is working now.
Thank you
