### ISSUE TITLE
The instruction for creating `aws-credential-process.json` is not described anyware

### ISSUE THREAD

**Issue by masaruyokoi** [Keeper-Security/aws-credential-process#8]
Hello.

I start to use the command `aws-credential-process`. I have searched carefully, but nowhere is there a description of how to create a configuration file　`aws-credential-process.json` .

I read following docs : 
- https://github.com/Keeper-Security/aws-credential-process/blob/main/README.md#ksm
- https://docs.keeper.io/secrets-manager/secrets-manager/integrations
- https://docs.keeper.io/secrets-manager/secrets-manager/integrations/aws-cli-credential-process

I will now read the source code and find out how to write the settings in JSON.

**Comment by masaruyokoi** [comment]
I understand as following:

``` json
{
 "clientId" : "XXXX (copy the value of `clientid` in ksm ini file)",
 "privateKey" : "XXXX (copy the value of `privatekey` in ksm ini file)",
 "appKey": "XXXX (copy the value of `appkey` in ksm ini file)",
 "hostname" : "keepersecurity.com", // depend on the region
 "appOwnerPublicKey" : "XXXX (copy the value of `appownerpublickey` in ksm ini file)",
 "serverPublicKeyId" : "XXXX (copy the value of `serverpublickeyid` in ksm ini file)"
}
```

I think the values for each config items are same as KSM python implements.

From the user's point of view, it is easier that the secret-manager-go read INI file generated by the ksm command.

**Comment by EndlessTrax** [comment]
Thanks for the issue, @masaruyokoi. 

The easiest way to get the `json` is from the UI. Here's the official documentation link showing you how - https://docs.keeper.io/secrets-manager/secrets-manager/about/secrets-manager-configuration#creating-a-secrets-manager-configuration 

I will make sure to add this to the README.md soon. Thanks for the spot.
